name: capstone_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - transformers
  - accelerate
  - pytest
  - reportlab
  - pypdf
  - flask
  - flask-sqlalchemy
  - sphinx
  - sphinx_rtd_theme