name: capstone_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - transformers
  - accelerate
  - pytest
  - reportlab
  - pypdf